# Generated by Django 5.1.4 on 2024-12-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'students',
                'managed': False,
            },
        ),
    ]
